[package]
name = "description-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.86", features = ["extra-traits"] }
proc-macro2 = "1.0.89"

[lib]
proc-macro = true
